-- DEPRECATED: This file is kept for historical reference only.
--
-- RailPulse now lives inside the shared Supabase project (alongside TrainPool)
-- in a dedicated `railpulse` schema. The authoritative migration is at:
--
--     railpulse/supabase/migrations/0001_railpulse_init.sql
--
-- That migration does NOT require TimescaleDB (Supabase free tier does not
-- include it). Do not run this file against Supabase.
